### ISSUE TITLE
Create a PR template with a checklist to ensure contribution guidelines are followed

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#309]
Adding a PR template via `.github/pull_request_template.md` will help ensure the contribution guidelines are being followed by making the PR contributor positively affirm that they are conforming to the guidelines.

This would include:

- Branch naming prefix 
- Affirmation that the PR addresses an issue that has been assigned to them
- Testing
- Documentation updates
- Typings

**Comment by endigo9740** [comment]
Including this for reference. A version of these were included in a PR that was not accepted:
https://github.com/Brain-Bones/skeleton/pull/303/files#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6b

Worth a bit more review for what we want to prompt and ask for specifically, but what was provided previously should be a good foundation.

**Comment by endigo9740** [comment]
Here's my suggestion...

## Before Submission

Please ensure you've completed the following before submitting your pull request.

- [ ] Did you [review this PR](https://skeleton.brainandbonesllc.com/docs/contributions) with core contributors on GitHub or Discord beforehand?
- [ ] Did you update documentation related to your new feature or changes?
- [ ] Did you you update and run tests before submission using `npm run test`?
- [ ] Does your branch follow our naming convention? ([see it here](https://skeleton.brainandbonesllc.com/docs/contributions))

## What does this PR address?

(provide a description here)

## Tips

- Tap "convert to draft" to indicate this is work in progress.
- Link to an issue using the verbiage [Fixes #XX](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- Linked issues will auto-close when the PR is merged.
