### ISSUE TITLE
a11y improvements (Help Wanted!)

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#41]
The aim is to improve overall accessibility across all component. This will be an on-going process that may be subdivided in to multiple parts.

[ARIA reference](https://www.w3.org/WAI/ARIA/apg/)

## A11y Tooling

Highly recommend [this video](https://www.youtube.com/watch?v=IaJtAzaFiJ4) showcasing each of the following tools.

* [axe DevTools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US)
* [Web Disability Simulator](https://chrome.google.com/webstore/detail/web-disability-simulator/olioanlbgbpmdlgjnnampnnlohigkjla?hl=en)
* [taba11y](https://chrome.google.com/webstore/detail/taba11y/aocppmckdocdjkphmofnklcjhdidgmga?hl=en)

# Part 1 (components)

The following suggestions were provided by user "Tropical" on the  [Svelte Discord
](https://discord.com/channels/457912077277855764/1001525322082173029/1001606363748773908)

### Accordions
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/
- [x] Convert to use [`<details>` and `<summary>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)
- [x] Support tab focus
- [x] Provide keyboard interaction
- [X] ARIA 

```
NOTES:
- Animation not well supported with the <details> content region, so no animations for now
- Both slot ids have been updated to match the semantic names of their wrapping elements
- ARIA require unique ids, so we're generating these automatically, but can be overwritten on-demand
```

### Buttons
https://www.w3.org/WAI/ARIA/apg/patterns/button/
- [x] Support tab focus
- [x] ARIA

```
NOTE: these updates are available to all components that embed a Button component
```

### List
https://www.w3.org/WAI/ARIA/apg/patterns/listbox/
- [x] Support tab focus
- [x] Provide keyboard interaction
- [x] ARIA

```
NOTES:
- ListGroup/ListItem have been completely rebuilt to better support a11y
- NavItem component has been removed, replace with ListItem
- List docs are updated to reflect all changes
```

### Menus
https://www.w3.org/WAI/ARIA/apg/patterns/menubutton/
https://www.w3.org/WAI/ARIA/apg/patterns/menu/
- [x] Support tab focus
- [X] Provide keyboard interaction
- [x] ARIA

```
NOTE: most Menu improvements are derived from the updates to the List/ListItem components
```

### Radio Groups
https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton/
- [x] Support tab focus
- [X] Provide keyboard interaction
- [x] ARIA

### Slide Toggles
https://www.w3.org/WAI/ARIA/apg/patterns/switch/
- [x] Support tab focus
- [x] Provide keyboard interaction
- [x] ARIA

### Tabs
https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/
- [x] Support tab focus
- [x] Provide keyboard interaction
- [x] ARIA

```
NOTE: users must provide their own 'tabpanel'.
```

**Comment by endigo9740** [comment]
(reserved)

**Comment by endigo9740** [comment]
(reserved)

**Comment by endigo9740** [comment]
(reserved)

**Comment by endigo9740** [comment]
(reserved)

**Comment by thomasbjespersen** [comment]
@endigo9740 Tabbing through the examples in the button page, skips the disabled toggle button.

**Comment by endigo9740** [comment]
Hey everyone! So great news regarding accessibility (a11y) updates. I've now completed the first round of updates improving a11y for ALL (yes all) components and utilities within Skeleton. The biggest areas of improvement include tab focus, keyboard interactions, and properly defined ARIA attributes. 

This is a rather large and impactful update that touches a little bit of everything in the entire library. Just take a look at the commit history here:

https://github.com/Brain-Bones/skeleton/commits/feat/a11y

However, it does come with a few notable and/or breaking changes:

- The Accordian no longer animates due to `<details>` and `<summary>` not yet properly supporting this natively. However, my hope is this can return in the future. BUT, a11y comes first!
- The List and it's children components have been rewritten from scratch. Plus the NavItem features have been merged into ListItem, so NavItem goes away
- Dialogs now utilize proper focus control, such as being able to tab between a prompt input and the cancel/confirm actions.

### Given the broad amount of changes, I am calling for your help with testing!

And no, you do NOT have to be an a11y expert to test these updates. Literally anyone that can pull down the branch can test. Mainly, I need help with regression testing. With minor updates in so many places, we need to ensure nothing has broken inadvertently. Just pull down the branch and start browsing the Doc site locally. Test everything you can between each component. Maybe create your own page to test different settings per the components with the most changes.

Long story short, if you're availble to help test, please let me know here, pull down the branch, and keep me posted as you progress. You can report all issues to the ticket above. The sooner testing concludes, the sooner we can get this update out to everyone! And the sooner I can move onto critical issues such as decoupling Skeleton from SvelteKit, new features and updates, etc.

The three attached screenshots demonstrate:

- Tab focus on the homepage, which utilizes a variety of different Skeleton components
- Colorblind support - though color/contrast/vision testing still needs a lot more work
- The axe Dev Tools accessibility score. Again highlighting our biggest gap remaining is vision-based issues

![Screen Shot 2022-08-14 at 1 47 33 PM](https://user-images.githubusercontent.com/1509726/184551549-c42e3091-64cb-4379-96fc-d42d861d8afc.png)

![Screen Shot 2022-08-14 at 1 48 24 PM](https://user-images.githubusercontent.com/1509726/184551552-dcb38ebf-f84d-4dc3-b372-bb10e1fee52c.png)

![Screen Shot 2022-08-14 at 1 50 10 PM](https://user-images.githubusercontent.com/1509726/184551553-d0e16fa0-a112-4518-90ce-1fe89d28becd.png)

**Comment by endigo9740** [comment]
For anyone interested in testing, here's the steps required:

1. Clone a version of Skeleton to your local device: `git clone https://github.com/Brain-Bones/skeleton.git`
2. Checkout the a11y code branch: `git checkout feat/a11y`
3. Move into the project directly: `cd skeleton`
4. Install NPM dependencies: `npm install`
5. Run a local dev server: `npm run dev` and point your browser to: `http://localhost:3000/`

Now that you have the project running locally, try and test the following:

* Navigate through the entire local site testing each and every component.
* Ensure there's no console log errors.
* Ensure the component examples work as you would expect
* Ensure the documented props match what's shown in the examples above
* Review the newly add `Accessibility` section at the bottom of each component doc page. Verify the ARIA link and all props match expectations
* (OPTIONAL) if you're feeling adventurous, create a new blank route page and start importing and testing each component with different props and settings. Especially ARIA attribute props.
* (OPTIONAL) if you wish to text a11y of each component, see the list of Chrome extensions at the top of the original post. These are pretty easy to use, but I'll provide a link to a great video intro below:

https://www.youtube.com/watch?v=IaJtAzaFiJ4

Finally, the critical areas of following should be the components with the large amount of updates. These include:

* The List/ListItem components - which have been completely rewritten from the ground up! Note that NavItem is no longer present, this was merged into ListItem.
* The Accordion - it now uses `<detail>` and `<summary>` tags for more native expansion groups. ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) page)
* Dialogs - these now attempt to capture and retain focus per the ARIA guidelines linked at the bottom of the docs page.
* For all other changes, see the notes included in the first handful of posts on this ticket!

If you find issues please report this in comments here. Thanks for your help!

**Comment by niktek** [comment]
Nice work on this so far :)

So doing a side by side comparison between master and feat-a11y and doing a scan with the axe extension for now:

There are two overall ARIA reported issues of colour and heading levels and some minor ones on specific pages.

But this comment focuses on actual Skeleton regressions found in RadioGroup and Slide Toggle no longer working and hence any dynamic preview of other components that use these two components on their docs page also don't work.

http://localhost:3000/components/avatars - Buttons and Slide Toggles no longer working
http://localhost:3000/components/buttons - Slide Toggle for Disabled no longer working
http://localhost:3000/components/data-tables - there are new aria props, but they aren't used in the example and it doesn't get picked up by the axe report.
http://localhost:3000/components/dividers - we have lost functionality to modify the divider
http://localhost:3000/components/progress-bars - Determinate and Height buttons are broken
http://localhost:3000/components/radio-groups - both justify and horz/vert sample don't click
http://localhost:3000/components/slide-toggles - all slide toggles broken

**Comment by endigo9740** [comment]
Awesome Nik, thanks. Really strange issues, but I'll take a look!

**Comment by endigo9740** [comment]
These changes have been moved into the `dev` branch but still open to additional testing before release.

**Comment by endigo9740** [comment]
Reopening this until @thomasbjespersen can finish QA on it.

**Comment by thomasbjespersen** [comment]
Taking this on @endigo9740.

**Comment by endigo9740** [comment]
FYI i'm closing this for now. Please keep me posted if you have any issues related to these changes @thomasbjespersen
